language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

virtualenv:
  system_site_packages: true

before_install:
  # Use Numpy 1.6.2 up to Python 3.3, then use pip.
  - 'if [ $TRAVIS_PYTHON_VERSION == "3.3" ]; then pip install numpy; else sudo apt-get install -qq python-numpy; fi;'
  #- sudo apt-get install -qq python-numpy
  #- sudo apt-get install -qq python3-numpy
  #- sudo apt-get install -qq python-scipy
  #- sudo apt-get install -qq python3-scipy
  #- sudo apt-get install python-matplotlib
  - pip install coveralls --use-mirrors

script:
  # Install dit
  - pip install .

  # Move to new directory so that dit is not imported from repository.
  # We need the full installation path.
  #
  # 2013-10-05
  #     We should import dit to determine its installation location.
  #     The reason is that if importing dit fails, then we won't
  #     change directories at all. Then when nosetests is run, zero
  #     tests will be run. So we no longer do the following:
  #
  ###- cd
  #### Move into the installation path.
  ###- cd `python -c "from __future__ import print_function;import dit;import os;print(os.path.split(dit.__file__)[0])"`
  #
  #     Instead, we'll use pip, grep, and awk. A bit fragile but it works.
  #
  - cd `pip show dit | grep Location | awk '{print $2"/dit"}'`

  # Export current directory for logs.
  - printenv PWD

  # Run nosetests.
  - nosetests -v --with-coverage --cover-erase --cover-package=dit

after_success:
  - coveralls
