name: dit_env

dependencies:
  - contextlib2
  - cvxopt
  - matplotlib
  - mkl
  - numpy
  - six >= 1.4
  - sphinx >= 1.3
  - pip:
    - ipython[nbconvert]
    - iterutils >= 0.1.6
    - releases
    - scipy >= 0.15
    - sphinxcontrib-bibtex
