name: dit_env

dependencies:
  - anaconda
  - contextlib2
  - cvxopt
  - matplotlib
  - numpy >= 1.6
  - scipy >= 0.15
  - six >= 1.4
  - sphinx >= 1.3
  - pip:
    - ipython[nbconvert]
    - iterutils >= 0.1.6
    - releases
    - sarge
    - sphinxcontrib-bibtex
