name: dit_env

dependencies:
  - contextlib2
  - cvxopt
  - numpy >= 1.6
  - releases
  - scipy >= 0.15
  - six >= 1.4
  - sphinx >= 1.3
  - sphinxcontrib-bibtex
  - pip:
    - ipython[nbconvert]
    - iterutils >= 0.1.6
