name: dit_env

dependencies:
  - contextlib2
  - cvxopt
  - matplotlib
  - numpy = 1.10.4
  - scipy = 0.15.0
  - six >= 1.4
  - sphinx >= 1.3
  - pip:
    - ipython[nbconvert]
    - iterutils >= 0.1.6
    - releases
    - sphinxcontrib-bibtex
