name: dit_env

dependencies:
  - contextlib2
  - cvxopt
  - matplotlib = 1.5
  - numpy = 1.11
  - scipy = 0.17
  - six >= 1.4
  - sphinx >= 1.3
  - pip:
    - ipython[nbconvert]
    - iterutils >= 0.1.6
    - releases
    - sphinxcontrib-bibtex
